# Grafana Monitoring
version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise
    user: "$UID:$GID"
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - /home/az/grafana-storage:/var/lib/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=web, websecure
      - traefik.http.routers.grafana.rule=Host(`perf.azertox.com`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=production
    restart: always
    networks:
     - traefik_default
networks:
  traefik_default:
    external: true
volumes:
  grafana-storage: {}