# NGINX Webserver
services:
  web:
    container_name: nginx-pi
    image: nginx:latest
    ports:
     - "8081:80"
    volumes:
     - /home/az/nginx-pi:/usr/share/nginx/html
     - /home/az/nginx-pi-conf:/etc/nginx/conf.d
    labels:
    - traefik.enable=true
    - traefik.http.routers.nginx.entrypoints=web, websecure
    - traefik.http.routers.nginx.rule=Host(`pi.azertox.com`)
    - traefik.http.routers.nginx.tls=true
    - traefik.http.routers.nginx.tls.certresolver=production
    restart: always
    networks:
    - traefik_default
networks:
  traefik_default:
    external: true