# Monitoring
version: '3.8'

services:
  grafana:
    image: grafana/grafana-enterprise
    user: "$UID:$GID"
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - /home/az/grafana-storage:/var/lib/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=web, websecure
      - traefik.http.routers.grafana.rule=Host(`perf.azertox.com`)
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=production
    restart: always
    networks:
      - traefik_default
      
  prometheus:
    image: prom/prometheus:v2.50.0
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - /home/az/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - /home/az/prometheus:/prometheus
    restart: always
    
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: always
    volumes:
      - /:/host:ro,rslave

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0     
    container_name: cadvisor
    ports:
      - 8082:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: always

networks:
  traefik_default:
    external: true

volumes:
  grafana-storage: {}
  prometheus-data:
    driver: local